-- ── Latina Exercitia — Chapter 7 Content: 3rd Declension Nouns ──
-- Run in Supabase SQL Editor after schema.sql, seed_data.sql, ch456_content.sql
-- Last updated: 2026-09-12
--
-- New drill type 'declension3'. Content shape:
--   lemma, display, meaning, gender (m/f/n), base, note,
--   paradigm { s:{5 cases}, p:{5 cases} }  — no vocative (identical to nominative)
-- Drill A (paradigm table) and drill B (base + gender) both read these rows.
--
-- Reversible: delete from drills where session_tag = 'wheelock_ch7';

insert into drills (type, lp_multiplier, session_tag, content) values
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "rex", "display": "rex, regis", "meaning": "m. — king", "gender": "m", "base": "reg", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "rex", "Genitive": "regis", "Dative": "regi", "Accusative": "regem", "Ablative": "rege"}, "p": {"Nominative": "reges", "Genitive": "regum", "Dative": "regibus", "Accusative": "reges", "Ablative": "regibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "homo", "display": "homo, hominis", "meaning": "m. — human being, man", "gender": "m", "base": "homin", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative. Stem changes vowel: homo but homin-. Only the genitive reveals it.", "paradigm": {"s": {"Nominative": "homo", "Genitive": "hominis", "Dative": "homini", "Accusative": "hominem", "Ablative": "homine"}, "p": {"Nominative": "homines", "Genitive": "hominum", "Dative": "hominibus", "Accusative": "homines", "Ablative": "hominibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "amor", "display": "amor, amoris", "meaning": "m. — love", "gender": "m", "base": "amor", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "amor", "Genitive": "amoris", "Dative": "amori", "Accusative": "amorem", "Ablative": "amore"}, "p": {"Nominative": "amores", "Genitive": "amorum", "Dative": "amoribus", "Accusative": "amores", "Ablative": "amoribus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "labor", "display": "labor, laboris", "meaning": "m. — labor, work, toil", "gender": "m", "base": "labor", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "labor", "Genitive": "laboris", "Dative": "labori", "Accusative": "laborem", "Ablative": "labore"}, "p": {"Nominative": "labores", "Genitive": "laborum", "Dative": "laboribus", "Accusative": "labores", "Ablative": "laboribus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "mos", "display": "mos, moris", "meaning": "m. — habit, custom, manner", "gender": "m", "base": "mor", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative. Plural mores has an idiomatic meaning: habits, morals, character.", "paradigm": {"s": {"Nominative": "mos", "Genitive": "moris", "Dative": "mori", "Accusative": "morem", "Ablative": "more"}, "p": {"Nominative": "mores", "Genitive": "morum", "Dative": "moribus", "Accusative": "mores", "Ablative": "moribus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "virtus", "display": "virtus, virtutis", "meaning": "f. — manliness, courage, virtue", "gender": "f", "base": "virtut", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "virtus", "Genitive": "virtutis", "Dative": "virtuti", "Accusative": "virtutem", "Ablative": "virtute"}, "p": {"Nominative": "virtutes", "Genitive": "virtutum", "Dative": "virtutibus", "Accusative": "virtutes", "Ablative": "virtutibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "civitas", "display": "civitas, civitatis", "meaning": "f. — state, citizenship", "gender": "f", "base": "civitat", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "civitas", "Genitive": "civitatis", "Dative": "civitati", "Accusative": "civitatem", "Ablative": "civitate"}, "p": {"Nominative": "civitates", "Genitive": "civitatum", "Dative": "civitatibus", "Accusative": "civitates", "Ablative": "civitatibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "pax", "display": "pax, pacis", "meaning": "f. — peace", "gender": "f", "base": "pac", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative. Nominative pax hides the stem pac-. Compare rex / reg-.", "paradigm": {"s": {"Nominative": "pax", "Genitive": "pacis", "Dative": "paci", "Accusative": "pacem", "Ablative": "pace"}, "p": {"Nominative": "paces", "Genitive": "pacum", "Dative": "pacibus", "Accusative": "paces", "Ablative": "pacibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "uxor", "display": "uxor, uxoris", "meaning": "f. — wife", "gender": "f", "base": "uxor", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative. Ends in -or but is feminine — gender follows sense (a wife), not the suffix rule.", "paradigm": {"s": {"Nominative": "uxor", "Genitive": "uxoris", "Dative": "uxori", "Accusative": "uxorem", "Ablative": "uxore"}, "p": {"Nominative": "uxores", "Genitive": "uxorum", "Dative": "uxoribus", "Accusative": "uxores", "Ablative": "uxoribus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "virgo", "display": "virgo, virginis", "meaning": "f. — maiden, virgin", "gender": "f", "base": "virgin", "note": "3rd declension consonant stem. Find the base by dropping -is from the genitive, then add the endings. Vocative is identical to the nominative. Stem adds -in-: virgo but virgin-.", "paradigm": {"s": {"Nominative": "virgo", "Genitive": "virginis", "Dative": "virgini", "Accusative": "virginem", "Ablative": "virgine"}, "p": {"Nominative": "virgines", "Genitive": "virginum", "Dative": "virginibus", "Accusative": "virgines", "Ablative": "virginibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "corpus", "display": "corpus, corporis", "meaning": "n. — body", "gender": "n", "base": "corpor", "note": "3rd declension neuter: nominative and accusative are always identical (plural ends in -a). Find the base from the genitive. Vocative is identical to the nominative. Looks like a 2nd declension -us noun but is 3rd declension neuter — the genitive corporis gives it away.", "paradigm": {"s": {"Nominative": "corpus", "Genitive": "corporis", "Dative": "corpori", "Accusative": "corpus", "Ablative": "corpore"}, "p": {"Nominative": "corpora", "Genitive": "corporum", "Dative": "corporibus", "Accusative": "corpora", "Ablative": "corporibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "carmen", "display": "carmen, carminis", "meaning": "n. — song, poem", "gender": "n", "base": "carmin", "note": "3rd declension neuter: nominative and accusative are always identical (plural ends in -a). Find the base from the genitive. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "carmen", "Genitive": "carminis", "Dative": "carmini", "Accusative": "carmen", "Ablative": "carmine"}, "p": {"Nominative": "carmina", "Genitive": "carminum", "Dative": "carminibus", "Accusative": "carmina", "Ablative": "carminibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "nomen", "display": "nomen, nominis", "meaning": "n. — name", "gender": "n", "base": "nomin", "note": "3rd declension neuter: nominative and accusative are always identical (plural ends in -a). Find the base from the genitive. Vocative is identical to the nominative.", "paradigm": {"s": {"Nominative": "nomen", "Genitive": "nominis", "Dative": "nomini", "Accusative": "nomen", "Ablative": "nomine"}, "p": {"Nominative": "nomina", "Genitive": "nominum", "Dative": "nominibus", "Accusative": "nomina", "Ablative": "nominibus"}}}'),
  ('declension3', 1.2, 'wheelock_ch7',
   '{"lemma": "tempus", "display": "tempus, temporis", "meaning": "n. — time, occasion, opportunity", "gender": "n", "base": "tempor", "note": "3rd declension neuter: nominative and accusative are always identical (plural ends in -a). Find the base from the genitive. Vocative is identical to the nominative. Like corpus: -us nominative, but 3rd declension neuter (genitive temporis).", "paradigm": {"s": {"Nominative": "tempus", "Genitive": "temporis", "Dative": "tempori", "Accusative": "tempus", "Ablative": "tempore"}, "p": {"Nominative": "tempora", "Genitive": "temporum", "Dative": "temporibus", "Accusative": "tempora", "Ablative": "temporibus"}}}');

-- ── Verify ──────────────────────────────────────────────────────
select id, content->>'display' as word, content->>'gender' as g
  from drills where type = 'declension3' order by id;
-- Expect 14 rows: 5 masculine, 5 feminine, 4 neuter.
